project_id = "oxojuprhrnlsbepykenc"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.analyze-file]
verify_jwt = false

[functions.generate-video]
verify_jwt = false
